.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "deepin-calculator" "1" "2021-3-11" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-calculator \- calculator for deepin.
.SH SYNOPSIS
deepin-calculator [OPTIONS...]
.SH DESCRIPTION
Calculator for UOS.
.PP
Calculator is a simple and easy-to-use desktop calculator. It supports addition, subtraction, multiplication and division with keyboard input perfectly matched, as well as symbolic fault-tolerant computing and calculation result linkage.
.SH OPTIONS
.PP
Note: command
.PP
-h, --help             Displays this help.
.PP
-v, --version          Displays version information.
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-calculator
.SH AUTHOR
.PP
.B deepin-calculator
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT jingzhou@\:uniontech.com
Jing Zhou
.ME
for the Debian Project (but may be used by others)
